name: Example Push Action
on: push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          wget https://github.com/mystic76/MicroG-RE/releases/download/1.0/topz.zip
          unzip topaz.zip
          git config user.name abhiram79
          git config user.email abhiramv670@gmail.com
          git add .
          git commit -m "initial commit (Device tree)"
          git push
